excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - "R.generated.swift"

opt_in_rules:
  - array_init
  - attributes
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_parameters
  - nimble_operator
  - number_separator
  - operator_usage_whitespace
  - override_in_extension
  - overridden_super_call
  - pattern_matching_keywords
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - required_enum_case
  - sorted_first_last
  - strict_fileprivate
  - switch_case_on_newline
#  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - unused_private_declaration
  - private_action
  - private_outlet
  - modifier_order

trailing_comma:
  mandatory_comma: false

force_cast: warning # implicitly
empty_count: warning
type_name: warning

disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - line_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
  - unused_closure_parameter
  - function_parameter_count
  - multiple_closures_with_trailing_closure
  - notification_center_detachment
  - unused_setter_value
  - implicit_return

# should be enabled
  - force_try
#  - force_unwrapping
#  - force_cast
#  - trailing_closure
#  - discouraged_object_literal
#  - type_body_length
